### ISSUE TITLE
swim.sh issues

### ISSUE THREAD

**Issue by fjcrabiffosse** [eurocontrol-swim/SWIM-TI-YP-prototype#1]
Hey @antavelos ,

Did some tests trying to run the deploy script from scratch following the README.md. Here are some issues I found:

1. When running `. ./swim.sh user_config` for the first time the user will get `Unable to find image 'swim-user-config:latest' locally`
    - Problem: when passing `user_config` variable to the script we have not run yet `clone_repos` and `build`.
    - Solution: We can solve this either via documentation, detailing the steps that need to be run before `user_config` or make `user_config` execute them if needed.

2. `usage` function should document `user_config` and option.

**Comment by antavelos** [comment]
@fjcrabiffosse 

1. Fixed by checking beforehand if the necessary image exists and building it if it does not. Updated also the README
2. Added doc for `user_config` command

[relevant commit](https://github.com/eurocontrol-swim/deploy/commit/0d81c337c57d86f372ed8e73ad56757ed49547a0)
