### ISSUE TITLE
swim-base image fails to build

### ISSUE THREAD

**Issue by fjcrabiffosse** [eurocontrol-swim/SWIM-TI-YP-prototype#2]
When running `./swim.sh build` for the first time the following error is generated:

```
Building swim-adsb
Step 1/11 : FROM swim-base
ERROR: Service 'swim-adsb' failed to build: pull access denied for swim-base, repository does not exist or may require 'docker login'
```

There seems to be some conflict with the conformance branch in the Dockerfile of base.

**Comment by antavelos** [comment]
@fjcrabiffosse fixed by removing the forgotten git conflict traces
