### ISSUE TITLE
nginx container image runs as root

### ISSUE THREAD

**Issue by fjcrabiffosse** [eurocontrol-swim/SWIM-TI-YP-prototype#9]
The nginx service still runs as root. We should run it with a specific user with restricted privileges.

A slightly old reference (hopefully still applicable): http://pjdietz.com/2016/08/28/nginx-in-docker-without-root.html

**Comment by antavelos** [comment]
[Done](e238174873ae6099fd8d311a0f2f4f7348572cfb)
